Repository AustinCodingAcademy/austincodingacademy.com, pull requests merged in 2019-04, with the labels that each got.

#126 header, footer, index updates
  _data/menus.yml
  _includes/footer.html
  index.html
Labels: Ready for review

#128 filter out private events
  events.js
Labels: Ready for review

#124 grads-page
  _config.yml
  _layouts/resume.html
  assets/css/main.css
  assets/images/ACA-logo-white-large.png
  grads.html
  hire/charles-cole.md
  tutors.html
Labels: Ready for review

#135 adjust positioning of button
  _includes/header.html
Labels: Ready for review

#151 create searchbar page
  robots.txt
  search.html
Labels: Ready for review

#138 create new dropdown About Us
  _data/menus.yml
  _includes/header.html
Labels: Ready for review

#153 Courses v2
  _data/menus.yml
  _includes/btn-apply.html
  _includes/campus-locations.html
  _includes/comparison-cards.html
  _includes/contact-form.html
  _includes/course-dates.html
  _includes/course-page.html
  _includes/curriculum.html
  _includes/footer.html
  _includes/observer-and-header-animation.html
  _includes/tuition-help.html
  _posts/2019-03-04-the-benefits-of-an-in-person-coding-bootcamp-vs-online-classes.md
  assets/css/main.css
  assets/images/hero-csharp.jpg
  assets/images/hero-javascript.jpg
  blog.html
  csharp.html
  faq.html
  financing.html
  grads.html
  index.html
  javascript.html
  landing.html
Labels: Ready for review

#152 replace hover-shadow-yellow
  _includes/btn-apply.html
  _includes/contact-form.html
  _includes/course-guide-form.html
  _includes/footer.html
  _includes/header.html
  apply.html
  assets/css/main.css
  financing.html
  instructor-apply.html
Labels: Conflict, Ready for review

#154 normalize spacing on non-hero pages
  _data/menus.yml
  apply.html
  assignment.html
  contact.html
  faq.html
  financing.html
  instructor-apply.html
  learn-to-code.html
  student-grievances.html
Labels: Conflict, Ready for review

#155 add temp content, spacing
  assets/css/main.css
  blog.html
Labels: Conflict, Ready for review

#156 fix buttons broken in conflict resolution
  _includes/btn-apply.html
  instructor-apply.html
Labels: Ready for review

#118 team page redesign
  _includes/amp.html
  assets/css/main.css
  team.html
Labels: Ready for review

#158 team page v2 ready
  assets/css/main.css
  team.html
Labels: Ready for review

#160 update instructors page to match team layout
  _includes/profiles-page.html
  instructors.html
  team.html
Labels: Ready for review

#159 copy
  _includes/course-guide-form.html
  blog.html
Labels: Ready for review

#161 amp-img, spacing
  assets/css/main.css
  grads.html
Labels: Ready for review

#163 fix permalink
  instructors.html
Labels: Ready for review

#162 add weekend tutoring notice, update layout
  tutors.html
Labels: Ready for review

#149 Forrest-Flowers [Complete].md
  hire/forrest-flowers.md
Labels: Hire

#139 [Maybe complete?] Alan Houston
  hire/alan-houston.md
Labels: Hire

#142 Katie Macaulay- Completed
  hire/katie-macaulay.md
Labels: Hire

#169 reduce & standardize fonts, margins; update resume
  _includes/campus-locations.html
  _includes/comparison-cards.html
  _includes/course-dates.html
  _includes/course-page.html
  _includes/curriculum.html
  _includes/events.html
  _includes/profiles-page.html
  _includes/tuition-help.html
  _layouts/resume.html
  apply.html
  assets/css/main.css
  assignment.html
  contact.html
  faq.html
  financing.html
  hire.html
  hire/charles-cole.md
  index.html
  instructor-apply.html
  instructors.html
  landing.html
  learn-to-code.html
  student-grievances.html
  tutors.html
Labels: Ready for review

#143 darwin-risser.md
  hire/darwin-risser.md
Labels: Hire

#171 update to layouts, fix resumes
  _layouts/resume.html
  hire.html
  hire/abby-gottlich.md
  hire/alan-houston.md
  hire/charles-cole.md
  hire/darwin-risser.md
  hire/erlangga-ramzy.md
  hire/forrest-flowers.md
  hire/gabe-flores.md
  hire/katie-macaulay.md
  hire/kevin-colten.md
Labels: Ready for review

#172 conditional amp-animation, reduce CSS
  _includes/amp.html
  _includes/btn-apply.html
  _includes/comparison-cards.html
  _includes/contact-form.html
  _includes/course-guide-form.html
  _includes/events.html
  _includes/referral-question.html
  apply.html
  assets/css/main.css
  blog.html
  index.html
  instructor-apply.html
  landing.html
Labels: Ready for review

#176 filter grads and hires
  _config.yml
  _layouts/resume.html
  grads.html
  hire.html
  hire/abby-gottlich.md
  hire/alan-houston.md
  hire/darwin-risser.md
  hire/erlangga-ramzy.md
  hire/forrest-flowers.md
  hire/gabe-flores.md
  hire/katie-macaulay.md
  hire/kevin-colten.md
Labels: Ready for review

#175 better tabindex practices
  _includes/contact-form.html
  _includes/header.html
  _includes/observer-and-header-animation.html
  _includes/profiles-page.html
  _includes/referral-question.html
  index.html
Labels: Ready for review

#173 add /hire to footer, /blog to header
  _data/menus.yml
Labels: Ready for review

#141 Christopher Willis hire page
  hire/christopher-willis.md
Labels: Hire

#144 WIP Patrick Kirby
  hire/patrick-kirby.md
Labels: Hire

#147 Create kellyn-barnes.md
  hire/kellyn-barnes.md
Labels: Hire

#150 [WIP] Lawerence Williams
  hire/lawerence-williams.md
Labels: Hire

#148 WIP wes-garbee.md
  hire/wes-garbee.md
Labels: Hire

#177 add Katie
  team.html
Labels: Ready for review

#178 remove default data
  hire.html
  hire/charles-cole.md
  hire/christopher-willis.md
  hire/kellyn-barnes.md
  hire/lawerence-williams.md
  hire/patrick-kirby.md
  hire/wes-garbee.md
Labels: Ready for review

#179 fonts in resume & footer icons updated
  _includes/footer.html
  _layouts/resume.html
  assets/css/main.css
Labels: Ready for review

#180 update hire faq & title
  faq.html
  hire.html
Labels: Ready for review

#181 author display
  _layouts/post.html
Labels: Ready for review

#182 Tutoring notices
  tutors.html
Labels: Ready for review

#185 new marketing tutors page
  _data/menus.yml
  _includes/tutors-list.html
  schedule-tutoring.html
  tutors.html
Labels: Ready for review

#186 update structured data
  _layouts/post.html
Labels: Ready for review

#202 Remove csharp
  _data/menus.yml
  _includes/campus-locations.html
  _includes/comparison-cards.html
  _includes/contact-form.html
  _includes/course-dates.html
  _includes/course-guide-form.html
  _includes/course-page.html
  _includes/curriculum.html
  _includes/elective-page.html
  _includes/events.html
  _includes/footer.html
  _includes/header.html
  _includes/scroll-menu-anim-disappearing.html
  _includes/scrolling-menu-observ-anim.html
  _includes/scrolling-menu-observ-footer.html
  _includes/scrolling-menu-observ-main.html
  _includes/scrolling-menu.html
  _posts/2019-01-23-aca-partners-with-austin-public-library-to-teach-teens-to-code.md
  _posts/2019-01-23-q-a-with-our-new-job-placement-course-director.md
  apply.html
  assets/css/main.css
  blog.html
  csharp.html
  faq.html
  javascript.html
Labels: Ready for review

#210 more inclusive logic
  grads.html
Labels: Ready for review

#203 Accessibility
  _data/menus.yml
  _includes/contact-form.html
  _includes/course-guide-form.html
  _includes/data-agreement.html
  _includes/events.html
  _includes/footer.html
  _includes/header.html
  _includes/profiles-page.html
  _includes/referral-question.html
  _includes/tutors-list.html
  _layouts/default.html
  _layouts/resume.html
  apply.html
  assets/css/main.css
  assets/documents/Austin-Coding-Academy-Course-Guide-Master.pdf
  assignment.html
  blog.html
  contact.html
  course-guide.html
  faq.html
  financing.html
  hire-edit.html
  hire.html
  index.html
  instructor-apply.html
  instructors.html
  landing.html
  learn-to-code.html
  student-grievances.html
  team.html
  thank-you.html
  web-development.html
  yarn.lock
Labels: Ready for review

#226 404
  404.html
  assets/css/main.css
Labels: Ready for review

#227 About Us dropdown & csharp page repaired
  _data/menus.yml
  _includes/elective-page.html
  csharp.html
Labels: Ready for review

#228 update titles and header order
  _data/menus.yml
  web-development.html
Labels: Ready for review
